name: Shell Commands From Udemy

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World from Mars"
      - name: multiline script 
        run: |
           node -v 
           npm -v
  #     - name: python Command
  #       run:
  #         import platform

  #         print(platform.processsor())
  #       shell: python
  # run-windows-commad:
  #   runs-on: windows-latest
  #   needs: ["run-shell-command"]
  #   steps:
  #     - name: Direcoty
  #     Powershell
  #       run: Get-Location
  #     - name: Directory Bash
  #       run: PWD
  #       shell: bash

